token:
 '7104169014:AAGiZEwf7EXxQMToUHm8fLEX5Tvhb-UXv7g'  # заменить на токен своего бота

#TOKEN

user_id:
  'USER_id' # заменить на название вашего бота

timezone:
  'Europe/Moscow'

timezone_common_name:
  'Moscow'
